# Welcome to Matt Learns Bookkeeping!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# If you look in the HTML files, you will see them accessed via {{ site.title }}, 
# {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Matt Learns Bookkeeping
email: mcurcio@duck.com
author: Matt Curcio
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "https://github.com/mcc-us/" # the subpath of your site
url: "" # base hostname & protocol
#twitter_username: 
github_username:  mcc-us

# Build settings
#theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Show a link to edit each page on GitHub
github_edit:
  enabled: true
  base_url: https://github.com/mcc-us/mcc-us.github.io/edit/master/

copyright:
  start_year: 2023
  url: /book.html

#
# Navigation menus
#

# Breadcrumbs for book contents.
# The book and contents pages need to be made manually.
# All "url" variables should have a leading slash.
bookcrumbs:
  book_url: /book.html
  contents_url: /contents.html
  book_icon: assets/gitbook/images/apple-touch-icon-precomposed-152.png

# Links shown above the TOC in the sidebar
# All "url" variables should have a leading slash.
sidebar_nav_top:
- label: Jekyll Chapterbook Theme
  url: /index.html

# Links shown below the TOC in the sidebar
# All "url" variables should have a leading slash.
sidebar_nav_bottom:
- label: Draft outline
  url: /outline.html
- label: Fork at GitHub
  url: https://github.com/jasongrimes/jekyll-chapterbook/fork

# Navigation shown at the bottom of the page
# All "url" variables should have a leading slash.
bottom_nav:
- label: Home
  url: /index.html
- label: Book
  url: /book.html
- label: GitHub
  url: https://github.com/jasongrimes/jekyll-chapterbook
- label: Privacy
  url: /privacy.html
